services:
  mysql:
    image: mysql:8.0
    container_name: url_shortener_db
    environment:
      MYSQL_DATABASE: url_shortener
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: url_shortener_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/url_shortener?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}

      JWT_SECRET: ${JWT_SECRET}
      ROOT_ADMIN_EMAIL: ${ROOT_ADMIN_EMAIL}
      ROOT_ADMIN_PASSWORD: ${ROOT_ADMIN_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: