spring:
  application:
    name: url-shortener
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300  # 5m
    refreshTokenExpiration: 604800  # 7d
    rootAdminEmail: ${ROOT_ADMIN_EMAIL}
    rootAdminPassword: ${ROOT_ADMIN_PASSWORD}
  profiles:
    active: dev